### ISSUE TITLE
Updating Anaconda.org Token on Appveyor

### ISSUE THREAD

**Issue by bashtage** [MacPython/statsmodels-wheels#44]
@matthew-brett the appyveyor build uses your account.  I'm happy to switch to mine it this is feasible.  If not, it would be a big help if you could encrypt a couple of tokens for uploading to anaconda.org's nightly wheels repo.

**Comment by matthew-brett** [comment]
It would probably be easier to switch to your account, do you agree?    I think that's just me disabling and you enabling builds on Appveyor ...

**Comment by bashtage** [comment]
I'm happy for you to switch to mine.

**Comment by bashtage** [comment]
I might need a permission for Appveyor though.  I don't see this repo when I look at my list.

**Comment by bashtage** [comment]
I see 
![image](https://user-images.githubusercontent.com/5585221/90114919-4ea5dd00-dd4b-11ea-908b-57330e79395b.png)

when I try to enable it for this repo.  Perhaps I can temporarily become an owner then you could take me off?

**Comment by matthew-brett** [comment]
Oh dammit - Appveyor is so confusing with its teams.

**Comment by bashtage** [comment]
The alternative would be to enable Azure for this repo.  I can copy what NumPy does pretty easily on Azure.

**Comment by matthew-brett** [comment]
Anything is fine for me.  But ... do you know how I can make you the owner of the Appveyor project?

**Comment by bashtage** [comment]
I don't think you can connect me to your account since these are individual account. If the MacPython account on appveyor org or individual?  We use a non-org account for appveyor on statsmodels so I don't know.

**Comment by matthew-brett** [comment]
statsmodels is on my account, yes.  I can add you to the MacPython account,
and try and move statsmodels there.  OK to risk destruction by trying that?

**Comment by bashtage** [comment]
There is nothign on appveyor that matters.

**Comment by bashtage** [comment]
My fork is up to date too

**Comment by matthew-brett** [comment]
I've told the matthew-brett Appveyor to build for no branches, so I hope triggering will stop there now.

Meanwhile, I enabled the 'statsmodels-builders' Github team for the MacPython account, and I set off a build.

https://ci.appveyor.com/project/MacPython/statsmodels-wheels

Does this give you any more access than you had before?

**Comment by bashtage** [comment]
Nothign yet.  This is what I see on Appveyor:

![image](https://user-images.githubusercontent.com/5585221/90122936-faecc100-dd55-11ea-85ba-2962ea52bc3c.png)

**Comment by matthew-brett** [comment]
OK - I sent an invitation to you, at your Gmail address - any luck now?

**Comment by bashtage** [comment]
Looks like it is working. Definitely have more permissions.

**Comment by bashtage** [comment]
I can add secrets now.  Thanks.

**Comment by matthew-brett** [comment]
Wow - I had begun to give in to despair.  Glad it worked.
